In [3]:
import pandas as pd

aptData = pd.read_excel('상도동 아파트 실거래가.xlsx',header=[16])
aptData

C:\Users\310-18\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202301,7,"104,000",21,2018,만양로 6,NaN,중개거래,서울 동작구
1,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202301,11,"130,000",15,2018,만양로 6,20230702.0,중개거래,서울 동작구
2,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202301,18,"129,500",9,2018,만양로 6,NaN,중개거래,서울 동작구
3,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202302,8,"106,000",28,2018,만양로 6,NaN,중개거래,서울 동작구
4,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202302,24,"100,000",2,2018,만양로 6,NaN,중개거래,서울 동작구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.9510,202303,12,"109,000",4,2013,상도로 346-2,NaN,중개거래,서울 동작구
207,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.9510,202303,23,"113,000",5,2013,상도로 346-2,NaN,중개거래,서울 동작구
208,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.9510,202304,1,"120,000",9,2013,상도로 346-2,NaN,중개거래,서울 동작구
209,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.8840,202306,16,"125,500",6,2013,상도로 346-2,NaN,중개거래,서울 동작구
210,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,120.9360,202306,24,"160,000",10,2013,상도로 346-2,NaN,중개거래,서울 동작구

In [4]:
aptData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시군구       211 non-null    object
 1   번지        211 non-null    object
 2   본번        211 non-null    int64
 3   부번        211 non-null    int64
 4   단지명       211 non-null    object
 5   전용면적(㎡)   211 non-null    float64
 6   계약년월      211 non-null    int64
 7   계약일       211 non-null    int64
 8   거래금액(만원)  211 non-null    object
 9   층         211 non-null    int64
 10  건축년도      211 non-null    int64
 11  도로명       211 non-null    object
 12  해제사유발생일   8 non-null      float64
 13  거래유형      211 non-null    object
 14  중개사소재지    211 non-null    object
dtypes: float64(2), int64(6), object(7)
memory usage: 24.9+ KB

In [5]:
aptData.head()

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202301,7,"104,000",21,2018,만양로 6,NaN,중개거래,서울 동작구
1,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202301,11,"130,000",15,2018,만양로 6,20230702.0,중개거래,서울 동작구
2,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202301,18,"129,500",9,2018,만양로 6,NaN,중개거래,서울 동작구
3,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202302,8,"106,000",28,2018,만양로 6,NaN,중개거래,서울 동작구
4,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202302,24,"100,000",2,2018,만양로 6,NaN,중개거래,서울 동작구

In [6]:
data = aptData.drop(index = [0], axis = 0)
data.head(20)

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
1,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202301,11,"130,000",15,2018,만양로 6,20230702.0,중개거래,서울 동작구
2,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202301,18,"129,500",9,2018,만양로 6,NaN,중개거래,서울 동작구
3,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202302,8,"106,000",28,2018,만양로 6,NaN,중개거래,서울 동작구
4,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202302,24,"100,000",2,2018,만양로 6,NaN,중개거래,서울 동작구
5,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.8746,202303,6,"123,500",3,2018,만양로 6,NaN,직거래,-
6,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.5905,202303,11,"106,000",12,2018,만양로 6,NaN,중개거래,서울 동작구
7,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202303,11,"134,000",14,2018,만양로 6,NaN,중개거래,서울 동작구
8,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202303,14,"135,000",15,2018,만양로 6,NaN,중개거래,서울 동작구
9,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202303,14,"134,000",11,2018,만양로 6,NaN,중개거래,"서울 관악구, 서울 동작구"
10,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.8746,202304,8,"132,000",16,2018,만양로 6,NaN,중개거래,서울 동작구
11,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202304,19,"114,500",16,2018,만양로 6,NaN,중개거래,서울 동작구
12,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202305,15,"117,000",10,2018,만양로 6,NaN,중개거래,서울 동작구
13,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202305,17,"137,500",5,2018,만양로 6,NaN,중개거래,서울 동작구
14,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202305,24,"113,000",11,2018,만양로 6,NaN,중개거래,서울 동작구
15,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,108.9843,202306,9,"167,000",14,2018,만양로 6,NaN,중개거래,서울 동작구
16,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,10,"138,000",21,2018,만양로 6,NaN,중개거래,서울 동작구
17,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,13,"140,000",6,2018,만양로 6,NaN,중개거래,서울 동작구
18,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,14,"142,500",12,2018,만양로 6,NaN,중개거래,서울 동작구
19,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,21,"143,000",1,2018,만양로 6,NaN,중개거래,서울 동작구
20,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,30,"138,500",4,2018,만양로 6,NaN,중개거래,"서울 강남구, 서울 동작구"

In [14]:
aptData.drop(aptData.index[0:17], axis = 0, inplace=True)
data.head()

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
1,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202301,11,"130,000",15,2018,만양로 6,20230702.0,중개거래,서울 동작구
2,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202301,18,"129,500",9,2018,만양로 6,NaN,중개거래,서울 동작구
3,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202302,8,"106,000",28,2018,만양로 6,NaN,중개거래,서울 동작구
4,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,59.7827,202302,24,"100,000",2,2018,만양로 6,NaN,중개거래,서울 동작구
5,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.8746,202303,6,"123,500",3,2018,만양로 6,NaN,직거래,-

In [15]:
aptData.reset_index()

,index,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,17,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,13,"140,000",6,2018,만양로 6,NaN,중개거래,서울 동작구
1,18,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,14,"142,500",12,2018,만양로 6,NaN,중개거래,서울 동작구
2,19,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,21,"143,000",1,2018,만양로 6,NaN,중개거래,서울 동작구
3,20,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,30,"138,500",4,2018,만양로 6,NaN,중개거래,"서울 강남구, 서울 동작구"
4,21,서울특별시 동작구 상도동,414,414,0,건영,32.8000,202209,30,"57,000",7,1997,만양로 26,NaN,중개거래,서울 동작구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,206,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.9510,202303,12,"109,000",4,2013,상도로 346-2,NaN,중개거래,서울 동작구
190,207,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.9510,202303,23,"113,000",5,2013,상도로 346-2,NaN,중개거래,서울 동작구
191,208,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.9510,202304,1,"120,000",9,2013,상도로 346-2,NaN,중개거래,서울 동작구
192,209,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.8840,202306,16,"125,500",6,2013,상도로 346-2,NaN,중개거래,서울 동작구
193,210,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,120.9360,202306,24,"160,000",10,2013,상도로 346-2,NaN,중개거래,서울 동작구

In [16]:
aptData.reset_index(drop = True, inplace = True)

In [17]:
aptData.head()

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,13,"140,000",6,2018,만양로 6,NaN,중개거래,서울 동작구
1,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,14,"142,500",12,2018,만양로 6,NaN,중개거래,서울 동작구
2,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,21,"143,000",1,2018,만양로 6,NaN,중개거래,서울 동작구
3,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,30,"138,500",4,2018,만양로 6,NaN,중개거래,"서울 강남구, 서울 동작구"
4,서울특별시 동작구 상도동,414,414,0,건영,32.8000,202209,30,"57,000",7,1997,만양로 26,NaN,중개거래,서울 동작구

In [18]:
data = aptData.drop(columns = ['번지','본번','부번'],axis = 1)
data.head()

,시군구,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 동작구 상도동,e편한세상상도노빌리티,84.9704,202306,13,"140,000",6,2018,만양로 6,NaN,중개거래,서울 동작구
1,서울특별시 동작구 상도동,e편한세상상도노빌리티,84.9704,202306,14,"142,500",12,2018,만양로 6,NaN,중개거래,서울 동작구
2,서울특별시 동작구 상도동,e편한세상상도노빌리티,84.9704,202306,21,"143,000",1,2018,만양로 6,NaN,중개거래,서울 동작구
3,서울특별시 동작구 상도동,e편한세상상도노빌리티,84.9704,202306,30,"138,500",4,2018,만양로 6,NaN,중개거래,"서울 강남구, 서울 동작구"
4,서울특별시 동작구 상도동,건영,32.8000,202209,30,"57,000",7,1997,만양로 26,NaN,중개거래,서울 동작구

In [19]:
data = aptData.drop(aptData.columns[1:4],axis = 1)
data.head()

,시군구,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 동작구 상도동,e편한세상상도노빌리티,84.9704,202306,13,"140,000",6,2018,만양로 6,NaN,중개거래,서울 동작구
1,서울특별시 동작구 상도동,e편한세상상도노빌리티,84.9704,202306,14,"142,500",12,2018,만양로 6,NaN,중개거래,서울 동작구
2,서울특별시 동작구 상도동,e편한세상상도노빌리티,84.9704,202306,21,"143,000",1,2018,만양로 6,NaN,중개거래,서울 동작구
3,서울특별시 동작구 상도동,e편한세상상도노빌리티,84.9704,202306,30,"138,500",4,2018,만양로 6,NaN,중개거래,"서울 강남구, 서울 동작구"
4,서울특별시 동작구 상도동,건영,32.8000,202209,30,"57,000",7,1997,만양로 26,NaN,중개거래,서울 동작구

In [20]:
aptData.drop(columns=['해제사유발생일','중개사소재지'],axis = 1, inplace= True)

In [21]:
aptData

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,거래유형
0,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,13,"140,000",6,2018,만양로 6,중개거래
1,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,14,"142,500",12,2018,만양로 6,중개거래
2,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,21,"143,000",1,2018,만양로 6,중개거래
3,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,30,"138,500",4,2018,만양로 6,중개거래
4,서울특별시 동작구 상도동,414,414,0,건영,32.8000,202209,30,"57,000",7,1997,만양로 26,중개거래
...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.9510,202303,12,"109,000",4,2013,상도로 346-2,중개거래
190,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.9510,202303,23,"113,000",5,2013,상도로 346-2,중개거래
191,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.9510,202304,1,"120,000",9,2013,상도로 346-2,중개거래
192,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.8840,202306,16,"125,500",6,2013,상도로 346-2,중개거래
193,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,120.9360,202306,24,"160,000",10,2013,상도로 346-2,중개거래

In [23]:
aptData.rename(columns={'전용면적(㎡)':'전용면적','거래금액(만원)':'거래금액'},inplace=True)
aptData

,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,층,건축년도,도로명,거래유형
0,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,13,"140,000",6,2018,만양로 6,중개거래
1,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,14,"142,500",12,2018,만양로 6,중개거래
2,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,21,"143,000",1,2018,만양로 6,중개거래
3,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,30,"138,500",4,2018,만양로 6,중개거래
4,서울특별시 동작구 상도동,414,414,0,건영,32.8000,202209,30,"57,000",7,1997,만양로 26,중개거래
...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.9510,202303,12,"109,000",4,2013,상도로 346-2,중개거래
190,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.9510,202303,23,"113,000",5,2013,상도로 346-2,중개거래
191,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.9510,202304,1,"120,000",9,2013,상도로 346-2,중개거래
192,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,84.8840,202306,16,"125,500",6,2013,상도로 346-2,중개거래
193,서울특별시 동작구 상도동,533,533,0,힐스테이트 상도 프레스티지,120.9360,202306,24,"160,000",10,2013,상도로 346-2,중개거래

In [24]:
aptData['평수']=aptData['전용면적']/3.3
aptData.head()

,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,층,건축년도,도로명,거래유형,평수
0,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,13,"140,000",6,2018,만양로 6,중개거래,25.748606
1,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,14,"142,500",12,2018,만양로 6,중개거래,25.748606
2,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,21,"143,000",1,2018,만양로 6,중개거래,25.748606
3,서울특별시 동작구 상도동,903,903,0,e편한세상상도노빌리티,84.9704,202306,30,"138,500",4,2018,만양로 6,중개거래,25.748606
4,서울특별시 동작구 상도동,414,414,0,건영,32.8000,202209,30,"57,000",7,1997,만양로 26,중개거래,9.939394